In [1]:
import sys
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # to display all interactive results, as opposed to 'last_expr'

When known to the interpreter, the script name and additional arguments thereafter are turned into a list of strings and assigned to the argv variable in the sys module. You can access this list by executing import sys. The length of the list is at least one; when no script and no arguments are given, sys.argv[0] is an empty string. When the script name is given as '-' (meaning standard input), sys.argv[0] is set to '-'. When -c command is used, sys.argv[0] is set to '-c'. When -m module is used, sys.argv[0] is set to the full name of the located module.

In [2]:
sys.argv

['/Users/adrshsrvstv/.venvs/default/lib/python3.13/site-packages/ipykernel_launcher.py',
 '-f',
 '/Users/adrshsrvstv/Library/Jupyter/runtime/kernel-86ff4661-a32b-4a98-9bbe-e9e25a89590d.json']

Division (/) always returns a float. To do floor division and get an integer result you can use the // operator; to calculate the remainder you can use %:

In [3]:
17 / 3

5.666666666666667

In [4]:
17 // 3

5

In [5]:
17 % 3

2

In [6]:
5**2 #power

25

In [7]:
'spam eggs'

'spam eggs'

In [8]:
"Paris rabbit got your back :)! Yay!"

'Paris rabbit got your back :)! Yay!'

In [9]:
'doesn\'t'  # use \' to escape the single quote...

"doesn't"

In [10]:
"doesn't"  # ...or use double quotes instead

"doesn't"

In [11]:
'"Yes," they said.'

'"Yes," they said.'

In [12]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

String literals can span multiple lines. One way is using triple-quotes: """...""" or '''...'''. End of lines are automatically included in the string, but it’s possible to prevent this by adding a \ at the end of the line. In the following example, the initial newline is not included:

In [13]:
print("""\
Usage: thingy [OPTIONS]
-h                        Display this usage message
-H hostname               Hostname to connect to
""")

Usage: thingy [OPTIONS]
-h                        Display this usage message
-H hostname               Hostname to connect to



In [14]:
#Strings can be concatenated (glued together) with the + operator, and repeated with *:
3 * 'un' + 'ium' 

'unununium'

Two or more string literals (i.e. the ones enclosed between quotes) next to each other are automatically concatenated.

In [15]:
'Py' 'thon'

'Python'

In [16]:
text = ('Put several strings within parentheses '
'to have them joined together.')
text

'Put several strings within parentheses to have them joined together.'

In [17]:
prefix = 'Py'

In [18]:
prefix 'thon'  # can't concatenate a variable and a string literal

SyntaxError: invalid syntax (957293534.py, line 1)

In [19]:
prefix + 'thon'

'Python'

In [20]:
word = 'Python'
word[0]  # character in position 0

'P'

In [21]:
word[5]  # character in position 5

'n'

In [22]:
word[-1]  # last character

'n'

In [23]:
word[-2]  # second-last character

'o'

In [24]:
word[-6] 


'P'

slicing is also supported. While indexing is used to obtain individual characters, slicing allows you to obtain a substring:

In [25]:
print(word[0:2])  # characters from position 0 (included) to 2 (excluded)

print(word[2:5])  # characters from position 2 (included) to 5 (excluded)


Py
tho


Slice indices have useful defaults; an omitted first index defaults to zero, an omitted second index defaults to the size of the string being sliced.

In [26]:
print(word[:2])   # character from the beginning to position 2 (excluded)

print(word[4:])   # characters from position 4 (included) to the end

print(word[-2:])  # characters from the second-last (included) to the end

Py
on
on


Note how the start is always included, and the end always excluded. This makes sure that s[:i] + s[i:] is always equal to s:

In [27]:
print(word[:2] + word[2:])

print(word[:4] + word[4:])


Python
Python


One way to remember how slices work is to think of the indices as pointing between characters, with the left edge of the first character numbered 0. Then the right edge of the last character of a string of n characters has index n, for example:

```
 +---+---+---+---+---+---+
 | P | y | t | h | o | n |
 +---+---+---+---+---+---+
 0   1   2   3   4   5   6
-6  -5  -4  -3  -2  -1
```

Attempting to use an index that is too large will result in an error, however, out of range slice indexes are handled gracefully when used for slicing:

In [28]:
print(word[42])

IndexError: string index out of range

In [29]:
print(word[4:42])

on


In [30]:
print(word[42:])

Python strings cannot be changed — they are immutable. Therefore, assigning to an indexed position in the string results in an error:

In [31]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

In [32]:
word[2:] = 'py'

TypeError: 'str' object does not support item assignment

In [33]:
word[:2] + 'py' #If you need a different string, you should create a new one:

'Pypy'

In [34]:
s = 'supercalifragilisticexpialidocious'
len(s)

34

In [35]:
squares = [1, 4, 9, 16, 25]
squares

[1, 4, 9, 16, 25]

In [36]:
squares[0]  # indexing returns the item

1

In [37]:
squares[-3:]  # slicing returns a new list


[9, 16, 25]

In [38]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Unlike strings, which are immutable, lists are a mutable type, i.e. it is possible to change their content:



In [39]:
cubes = [1, 8, 27, 65, 125]
cubes[3] = 64  # replace the wrong value
cubes

[1, 8, 27, 64, 125]

In [40]:
cubes.append(7 ** 3)
cubes

[1, 8, 27, 64, 125, 343]

Simple assignment in Python never copies data. When you assign a list to a variable, the variable refers to the existing list. Any changes you make to the list through one variable will be seen through all other variables that refer to it.:

In [41]:
rgb = ["Red", "Green", "Blue"]
rgba = rgb
id(rgb) == id(rgba)  # they reference the same object

True

In [42]:
rgba.append("Alph")
rgb

['Red', 'Green', 'Blue', 'Alph']

All slice operations return a new list containing the requested elements. This means that the following slice returns a shallow copy of the list.

The difference between shallow and deep copying is only relevant for compound objects (objects that contain other objects, like lists or class instances):

- A shallow copy constructs a new compound object and then (to the extent possible) inserts references into it to the objects found in the original.
- A deep copy constructs a new compound object and then, recursively, inserts copies into it of the objects found in the original.

Two problems often exist with deep copy operations that don’t exist with shallow copy operations:

- Recursive objects (compound objects that, directly or indirectly, contain a reference to themselves) may cause a recursive loop.
- Because deep copy copies everything it may copy too much, such as data which is intended to be shared between copies.

In [43]:
correct_rgba = rgba[:]
correct_rgba[-1] = "Alpha"
correct_rgba
rgba
len(rgba)

['Red', 'Green', 'Blue', 'Alpha']

['Red', 'Green', 'Blue', 'Alph']

4

In [44]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
letters

# replace some values
letters[2:5] = ['C', 'D', 'E']
letters

# now remove them
letters[2:5] = []
letters

# clear the list by replacing all the elements with an empty list
letters[:] = []
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

['a', 'b', 'C', 'D', 'E', 'f', 'g']

['a', 'b', 'f', 'g']

[]

In [45]:
# It is possible to nest lists (create lists containing other lists), for example:
a = ['a', 'b', 'c']
n = [1, 2, 3]
x = [a, n]
x

[['a', 'b', 'c'], [1, 2, 3]]

In [46]:
x[0]
x[0][1]

['a', 'b', 'c']

'b'

In Python, like in C, any non-zero integer value is true; zero is false. The condition may also be a string or list value, in fact any sequence; anything with a non-zero length is true, empty sequences are false. The test used in the example is a simple comparison. The standard comparison operators are written the same as in C: < (less than), > (greater than), == (equal to), <= (less than or equal to), >= (greater than or equal to) and != (not equal to).

In [47]:
a, b = 0, 1
while a < 1000:
    print(a, end=',') # The keyword argument end can be used to avoid the newline after the output, or end the output with a different string:
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

In [48]:
x = int(input("Please enter an integer: "))

if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

Please enter an integer:  67


More


A match statement takes an expression and compares its value to successive patterns given as one or more case blocks. This is superficially similar to a switch statement in C, Java or JavaScript (and many other languages), but it’s more similar to pattern matching in languages like Rust or Haskell. Only the first pattern that matches gets executed and it can also extract components (sequence elements or object attributes) from the value into variables.

Note the last block: the “variable name” _ acts as a wildcard and never fails to match. If no case matches, none of the branches is executed.

In [49]:
def http_error(status):
    match status:
        case 400:
            return "Bad request"
        case 404:
            return "Not found"
        case 418:
            return "I'm a teapot"
        case 401 | 403 | 405:
            return "Not allowed"
        case _:
            return "Something's wrong with the internet"

http_error(405)

'Not allowed'

The first pattern has two literals, and can be thought of as an extension of the literal pattern shown above. But the next two patterns combine a literal and a variable, and the variable binds a value from the subject (point). The fourth pattern captures two values, which makes it conceptually similar to the unpacking assignment (x, y) = point.

In [50]:
# point is an (x, y) tuple
point=2,3
match point:
    case (0, 0):
        print("Origin")
    case (0, y):
        print(f"Y={y}")
    case (x, 0):
        print(f"X={x}")
    case (x, y):
        print(f"X={x}, Y={y}")
    case _:
        raise ValueError("Not a point")

X=2, Y=3


In [51]:
# Measure some strings:
words = ['cat', 'window', 'defenestrate']
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


Code that modifies a collection while iterating over that same collection can be tricky to get right. Instead, it is usually more straight-forward to loop over a copy of the collection or to create a new collection:

In [52]:
# Create a sample collection
users = {'Hans': 'active', 'Éléonore': 'inactive', '景太郎': 'active'}

# Strategy:  Iterate over a copy
for user, status in users.copy().items():
    if status == 'inactive':
        del users[user]
print(users)

# Strategy:  Create a new collection
active_users = {}
for user, status in users.items():
    if status == 'active':
        active_users[user] = status

{'Hans': 'active', '景太郎': 'active'}


In [53]:
list(range(5, 10))


list(range(0, 10, 3))


list(range(-10, -100, -30))

[5, 6, 7, 8, 9]

[0, 3, 6, 9]

[-10, -40, -70]

To iterate over the indices of a sequence, you can combine range() and len() as follows:

In [54]:
a = ['Mary', 'had', 'a', 'little', 'lamb']
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


In [55]:
range(10) #range is an iterable but not an actual list

range(0, 10)

When a final formal parameter of the form **name is present, it receives a dictionary (see Mapping Types — dict) containing all keyword arguments except for those corresponding to a formal parameter. This may be combined with a formal parameter of the form *name (described in the next subsection) which receives a tuple containing the positional arguments beyond the formal parameter list. (*name must occur before **name.) For example, if we define a function like this:

Note that the order in which the keyword arguments are printed is guaranteed to match the order in which they were provided in the function call.

A function definition may look like:

```
    def f(pos1, pos2, /, pos_or_kwd, *, kwd1, kwd2):
      -----------    ----------     ----------
        |             |                  |
        |        Positional or keyword   |
        |                                - Keyword only
         -- Positional only
```
where / and * are optional. If used, these symbols indicate the kind of parameter by how the arguments may be passed to the function: positional-only, positional-or-keyword, and keyword-only. Keyword parameters are also referred to as named parameters.

In [56]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    print(type(keywords))
    print(keywords)
    for kw, val in keywords.items(): # alternately: for kw in keywords:
        print(kw, ":", val)          #    print(kw, ":", keywords[kw])

In [57]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
<class 'dict'>
{'shopkeeper': 'Michael Palin', 'client': 'John Cleese', 'sketch': 'Cheese Shop Sketch'}
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


In [58]:
l = [1,2,3,5,6]
print(*l) # list unpacking
print(l)

1 2 3 5 6
[1, 2, 3, 5, 6]


In [59]:
def parrot(voltage, state='a stiff', action='voom'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.", end=' ')
    print("E's", state, "!")

d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}
parrot(**d) # dict unpacking

-- This parrot wouldn't VOOM if you put four million volts through it. E's bleedin' demised !


Small anonymous functions can be created with the lambda keyword. This function returns the sum of its two arguments: lambda a, b: a+b. Lambda functions can be used wherever function objects are required. They are syntactically restricted to a single expression. Semantically, they are just syntactic sugar for a normal function definition. Like nested function definitions, lambda functions can reference variables from the containing scope:

In [60]:
def make_incrementor(n):
    return lambda x: x + n

f = make_incrementor(42)
f(3)

45

In [61]:
pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]
pairs.sort(key=lambda pair: pair[1]) #custom sorting based on second key of tuple
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

Function annotations are completely optional metadata information about the types used by user-defined functions (see PEP 3107 and PEP 484 for more information).

Annotations are stored in the __annotations__ attribute of the function as a dictionary and have no effect on any other part of the function. Parameter annotations are defined by a colon after the parameter name, followed by an expression evaluating to the value of the annotation. Return annotations are defined by a literal ->, followed by an expression, between the parameter list and the colon denoting the end of the def statement. The following example has a required argument, an optional argument, and the return value annotated:

In [62]:
def f(ham: str, eggs: str = 'eggs') -> str:
    print("Annotations:", f.__annotations__)
    print("Arguments:", ham, eggs)
    return ham + ' and ' + eggs

f('spam', 'burger')

Annotations: {'ham': <class 'str'>, 'eggs': <class 'str'>, 'return': <class 'str'>}
Arguments: spam burger


'spam and burger'

In [63]:
# docstring
def my_function():
    """Do nothing, but document it.

    No, really, it doesn't do anything.
    """
    pass

print(my_function.__doc__)

Do nothing, but document it.

No, really, it doesn't do anything.



In [64]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits.count('apple')

fruits.count('tangerine')

fruits.index('banana')

fruits.index('banana', 4)  # Find next banana starting at position 4

fruits.reverse()
fruits

fruits.append('grape')
fruits

fruits.sort()
fruits

fruits.pop()

2

0

3

6

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

'pear'

You might have noticed that methods like insert, remove or sort that only modify the list have no return value printed – they return the default None. [1] This is a design principle for all mutable data structures in Python.

### Using Lists as stack

The list methods make it very easy to use a list as a stack, where the last element added is the first element retrieved (“last-in, first-out”). To add an item to the top of the stack, use append(). To retrieve an item from the top of the stack, use pop() without an explicit index.

In [65]:
stack = [3, 4, 5]
stack.append(6)
stack.append(7)
stack

stack.pop()

stack

stack.pop()

stack.pop()

stack


[3, 4, 5, 6, 7]

7

[3, 4, 5, 6]

6

5

[3, 4]

###  Using Lists as Queues

It is also possible to use a list as a queue, where the first element added is the first element retrieved (“first-in, first-out”); however, lists are not efficient for this purpose. While appends and pops from the end of list are fast, doing inserts or pops from the beginning of a list is slow (because all of the other elements have to be shifted by one).

To implement a queue, use collections.deque which was designed to have fast appends and pops from both ends. For example:


In [66]:
from collections import deque
queue = deque(["Eric", "John", "Michael"])
queue.append("Terry")           # Terry arrives
queue
queue.append("Graham")          # Graham arrives
queue
queue.popleft()                 # The first to arrive now leaves

queue.popleft()                 # The second to arrive now leaves

queue.pop()                       # pop from end not front 
queue # Remaining queue in order of arrival

deque(['Eric', 'John', 'Michael', 'Terry'])

deque(['Eric', 'John', 'Michael', 'Terry', 'Graham'])

'Eric'

'John'

'Graham'

deque(['Michael', 'Terry'])

In [67]:
pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]

for i,(k,v) in enumerate(pairs):
    print("index", i, "=",k,":",v)

index 0 = 1 : one
index 1 = 2 : two
index 2 = 3 : three
index 3 = 4 : four


In [68]:
for k,v in pairs:
    print(k,v)

1 one
2 two
3 three
4 four


In [69]:
d = {"voltage": "four million", "state": "bleedin' demised", "action": "VOOM"}
for k,v in d.items():
    print(k,":",v)

voltage : four million
state : bleedin' demised
action : VOOM


In [70]:
for i, p in enumerate(d.items()):
    print(i,":",p)

0 : ('voltage', 'four million')
1 : ('state', "bleedin' demised")
2 : ('action', 'VOOM')


### list comprehension


In [71]:
list(map(lambda x: x**2, range(10)))

[x**2 for x in range(10)]

#both are equivalent

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

A list comprehension consists of brackets containing an expression followed by a for clause, then zero or more for or if clauses. The result will be a new list resulting from evaluating the expression in the context of the for and if clauses which follow it. For example, this listcomp combines the elements of two lists if they are not equal:

In [72]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]


[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [73]:
#equivalent code
combs = []
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))

combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

In [74]:
vec = [-4, -2, 0, 2, 4]
# create a new list with the values doubled
[x*2 for x in vec]

# filter the list to exclude negative numbers
[x for x in vec if x >= 0]

# apply a function to all the elements
[abs(x) for x in vec]

# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
[weapon.strip() for weapon in freshfruit]

# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem] # IMPORTANT!!!!!!

# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

# the tuple must be parenthesized, otherwise an error is raised
# [x, x**2 for x in range(6)]

[-8, -4, 0, 4, 8]

[0, 2, 4]

[4, 2, 0, 2, 4]

['banana', 'loganberry', 'passion fruit']

[1, 2, 3, 4, 5, 6, 7, 8, 9]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

The initial expression in a list comprehension can be any arbitrary expression, including another list comprehension.

In [75]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [76]:
# equivalent to
transposed = []
for i in range(4):
    transposed.append([row[i] for row in matrix])

transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [77]:
# but also
list(zip(*matrix))


[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

## zip() 

returns an iterator of tuples, where the i-th tuple contains the i-th element from each of the argument iterables.

Another way to think of zip() is that it turns rows into columns, and columns into rows. This is similar to transposing a matrix.

zip() is lazy: The elements won’t be processed until the iterable is iterated on, e.g. by a for loop or by wrapping in a list.

In [78]:
# Iterate over several iterables in parallel, producing tuples with an item from each one.

for item in zip([1, 2, 3], ['sugar', 'spice', 'everything nice']):
    print(item)

(1, 'sugar')
(2, 'spice')
(3, 'everything nice')


In [79]:
list(zip(range(3), ['fee', 'fi', 'fo', 'fum'])) # By default, zip() stops when the shortest iterable is exhausted. 

[(0, 'fee'), (1, 'fi'), (2, 'fo')]

In [80]:
list(zip(range(3), ['fee', 'fi', 'fo', 'fum'], strict=True)) # to ensure both iterables must have same length

ValueError: zip() argument 2 is longer than argument 1

In [81]:
a = [-1, 1, 66.25, 333, 333, 1234.5]
del a[0]
a

del a[2:4]
a

del a[:]
a

[1, 66.25, 333, 333, 1234.5]

[1, 66.25, 1234.5]

[]

In [82]:
del a
a

NameError: name 'a' is not defined

### Tuples

We saw that lists and strings have many common properties, such as indexing and slicing operations. They are two examples of sequence data types (see Sequence Types — list, tuple, range). Since Python is an evolving language, other sequence data types may be added. There is also another standard sequence data type: the tuple.

Though tuples may seem similar to lists, they are often used in different situations and for different purposes. Tuples are immutable, and usually contain a heterogeneous sequence of elements that are accessed via unpacking (see later in this section) or indexing (or even by attribute in the case of namedtuples). Lists are mutable, and their elements are usually homogeneous and are accessed by iterating over the list.

In [83]:
t = 12345, 54321, 'hello!'
t[0]

t

# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)
u

# Tuples are immutable:
t[0] = 88888

12345

(12345, 54321, 'hello!')

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

TypeError: 'tuple' object does not support item assignment

In [84]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])
v[1][2]=5
v

([1, 2, 3], [3, 2, 5])

A special problem is the construction of tuples containing 0 or 1 items: the syntax has some extra quirks to accommodate these. Empty tuples are constructed by an empty pair of parentheses; a tuple with one item is constructed by following a value with a comma (it is not sufficient to enclose a single value in parentheses). Ugly, but effective. For example:

In [85]:
empty = ()
singleton = 'hello',    # <-- note trailing comma
len(empty)

len(singleton)

singleton

0

1

('hello',)

The statement t = 12345, 54321, 'hello!' is an example of tuple packing: the values 12345, 54321 and 'hello!' are packed together in a tuple. The reverse operation is also possible:

In [86]:
x, y, z = t
x
y
z

12345

54321

'hello!'

This is called, appropriately enough, sequence unpacking and works for any sequence on the right-hand side. Sequence unpacking requires that there are as many variables on the left side of the equals sign as there are elements in the sequence. Note that multiple assignment is really just a combination of tuple packing and sequence unpacking.

In [87]:
x, y, z = "abc"
x
y
z

'a'

'b'

'c'

In [88]:
x, y, z = [1,3,5]
x
y
z

1

3

5

## Sets

set is an unordered collection with no duplicate elements. Basic uses include membership testing and eliminating duplicate entries. Set objects also support mathematical operations like union, intersection, difference, and symmetric difference.

Curly braces or the set() function can be used to create sets. Note: to create an empty set you have to use set(), not {}; the latter creates an empty dictionary, a data structure that we discuss in the next section.

In [89]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
print(basket)                      # show that duplicates have been removed

'orange' in basket                 # fast membership testing

'crabgrass' in basket


# Demonstrate set operations on unique letters from two words

a = set('abracadabra')
b = set('alacazam')
a                                  # unique letters in a

a - b                              # letters in a but not in b

a | b                              # letters in a or b or both

a & b                              # letters in both a and b

a ^ b                              # letters in a or b but not both


{'banana', 'orange', 'apple', 'pear'}


True

False

{'a', 'b', 'c', 'd', 'r'}

{'b', 'd', 'r'}

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

{'a', 'c'}

{'b', 'd', 'l', 'm', 'r', 'z'}

In [90]:
# Similarly to list comprehensions, set comprehensions are also supported:
a = {x for x in 'abracadabra' if x not in 'abc'}
a

{'d', 'r'}

### Dict

Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like append() and extend().

It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: {}. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

Performing list(d) on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use sorted(d) instead). To check whether a single key is in the dictionary, use the in keyword.

In [91]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

tel['jack']

del tel['sape']
tel['irv'] = 4127
tel

list(tel)

sorted(tel)

'guido' in tel

'jack' not in tel


{'jack': 4098, 'sape': 4139, 'guido': 4127}

4098

{'jack': 4098, 'guido': 4127, 'irv': 4127}

['jack', 'guido', 'irv']

['guido', 'irv', 'jack']

True

False

In [92]:
# The dict() constructor builds dictionaries directly from sequences of key-value pairs:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])


{'sape': 4139, 'guido': 4127, 'jack': 4098}

In [93]:
# dict comprehensions can be used to create dictionaries from arbitrary key and value expressions:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

In [94]:
# When the keys are simple strings, it is sometimes easier to specify pairs using keyword arguments:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

## Looping techniques


In [95]:
# When looping through dictionaries, the key and corresponding value can be retrieved at the same time using the items() method.
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for k, v in knights.items():
    print(k, v)

knights.items() 
[*knights.items()] # is an iterable/sequence of dict tuples. So can use enumerate also in a weird way

for i, (a,b) in enumerate(knights.items()):
    print(i,":", a, ",", b)

gallahad the pure
robin the brave


dict_items([('gallahad', 'the pure'), ('robin', 'the brave')])

[('gallahad', 'the pure'), ('robin', 'the brave')]

0 : gallahad , the pure
1 : robin , the brave


In [96]:
# When looping through a sequence, the position index and corresponding value can be retrieved at the same time using the enumerate() function.

for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


In [97]:
# To loop over two or more sequences at the same time, the entries can be paired with the zip() function.

questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


In [98]:
#To loop over a sequence in reverse, first specify the sequence in a forward direction and then call the reversed() function.

for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


In [99]:
# To loop over a sequence in sorted order, use the sorted() function which returns a new sorted list while leaving the source unaltered.
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for i in sorted(basket):
    print(i)

apple
apple
banana
orange
orange
pear


In [100]:
# use sorted() in combination with set() over a sequence to loop over unique elements of the sequence in sorted order.
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


In [101]:
(1, 2, 3)              < (1, 2, 4)
[1, 2, 3]              < [1, 2, 4]
'ABC' < 'C' < 'Pascal' < 'Python'
(1, 2, 3, 4)           < (1, 2, 4)
(1, 2)                 < (1, 2, -1)
(1, 2, 3)             == (1.0, 2.0, 3.0)
(1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4)

True

True

True

True

True

True

True

# Modules

A module is a file containing Python definitions and statements. The file name is the module name with the suffix .py appended. Within a module, the module’s name (as a string) is available as the value of the global variable __name__. For instance, use your favorite text editor to create a file called fibo.py in the current directory with the following contents:

In [102]:
# Fibonacci numbers module

def fib(n):    # write Fibonacci series up to n
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

def fib2(n):   # return Fibonacci series up to n
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)
        a, b = b, a+b
    return result

In [104]:
# now you can do 
# import fibo

# fibo.fib(1000)

# fibo.fib2(100)

# fibo.__name__

A module can contain executable statements as well as function definitions. These statements are intended to initialize the module. They are executed only the first time the module name is encountered in an import statement. [1] (They are also run if the file is executed as a script.)

Each module has its own private namespace, which is used as the global namespace by all functions defined in the module. Thus, the author of a module can use global variables in the module without worrying about accidental clashes with a user’s global variables. On the other hand, if you know what you are doing you can touch a module’s global variables with the same notation used to refer to its functions, modname.itemname.

Modules can import other modules. It is customary but not required to place all import statements at the beginning of a module (or script, for that matter). The imported module names, if placed at the top level of a module (outside any functions or classes), are added to the module’s global namespace.

There is a variant of the import statement that imports names from a module directly into the importing module’s namespace. For example:

In [108]:
# from fibo import fib, fib2
# fib(500)

# This does not introduce the module name from which the imports are taken in the local namespace (so in the example, fibo is not defined).

# You can also do

# from fibo import *

# and 

# import fibo as fib
# fib.fib(500

# or

# from fibo import fib as fibonacci
# fibonacci(500)

### Executing modules as scripts

When you run a Python module with

```python
python fibo.py <arguments>
```

the code in the module will be executed, just as if you imported it, but with the __name__ set to "__main__". That means that by adding this code at the end of your module:

```python
if __name__ == "__main__":
    import sys
    fib(int(sys.argv[1]))
```

you can make the file usable as a script as well as an importable module, because the code that parses the command line only runs if the module is executed as the “main” file.

This is often used either to provide a convenient user interface to a module, or for testing purposes (running the module as a script executes a test suite).



### Module paths and standard modules

The variable sys.path is a list of strings that determines the interpreter’s search path for modules. It is initialized to a default path taken from the environment variable PYTHONPATH, or from a built-in default if PYTHONPATH is not set. You can modify it using standard list operations:

In [113]:
import sys
sys.path.append('/ufs/guido/lib/python')
a=10

In [ ]:
dir() #all names currently defined 

In [ ]:
dir(sys) # all names in sys module

## Packages

When importing the package, Python searches through the directories on sys.path looking for the package subdirectory.

The __init__.py files are required to make Python treat directories containing the file as packages.  This prevents directories with a common name, such as string, from unintentionally hiding valid modules that occur later on the module search path. In the simplest case, __init__.py can just be an empty file, but it can also execute initialization code for the package or set the __all__ variable, described later.

```
sound/                          Top-level package
      __init__.py               Initialize the sound package
      formats/                  Subpackage for file format conversions
              __init__.py
              wavread.py
              wavwrite.py
              aiffread.py
              aiffwrite.py
              auread.py
              auwrite.py
              ...
      effects/                  Subpackage for sound effects
              __init__.py
              echo.py
              surround.py
              reverse.py
              ...
      filters/                  Subpackage for filters
              __init__.py
              equalizer.py
              vocoder.py
              karaoke.py
              ...
```

In [122]:
# Users of the package can import individual modules from the package, for example:

# import sound.effects.echo

# or 

# from sound.effects import echo

Note that when using from package import item, the item can be either a submodule (or subpackage) of the package, or some other name defined in the package, like a function, class or variable. The import statement first tests whether the item is defined in the package; if not, it assumes it is a module and attempts to load it. If it fails to find it, an ImportError exception is raised.

Contrarily, when using syntax like import item.subitem.subsubitem, each item except for the last must be a package; the last item can be a module or a package but can’t be a class or function or variable defined in the previous item.

#### Import *

Now what happens when the user writes from sound.effects import *? 

The import statement uses the following convention: if a package’s __init__.py code defines a list named __all__, it is taken to be the list of module names that should be imported when from package import * is encountered. It is up to the package author to keep this list up-to-date when a new version of the package is released. 

For example, the file sound/effects/__init__.py could contain the following code:

In [126]:
__all__ = ["echo", "surround", "reverse"]

# This would mean that from sound.effects import * would import the three named submodules of the sound.effects package.

# Input and Output

In [129]:
#formatted strings let you use variables
a = 10 
animal = 'kittens'
say = f'There are {a} {animal} in my jacket!!!'
print(say)

There are 10 kittens in my jacket!!!


Formatted string literals (also called f-strings for short) let you include the value of Python expressions inside a string by prefixing the string with f or F and writing expressions as {expression}.

In [152]:
import math
print(f'The value of pi is approximately {math.pi:.3f}.') # :.3frounds pi to three places after the decimal

The value of pi is approximately 3.142.


In [137]:
# Passing an integer after the ':' will cause that field to be a minimum number of characters wide. This is useful for making columns line up.table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 7678}
for name, phone in table.items():
    print(f'{name:10} ==> {phone:10d}')

Sjoerd     ==>       4127
Jack       ==>       4098
Dcab       ==>       7678


#### The = specifier can be used to expand an expression to the text of the expression, an equal sign, then the representation of the evaluated expression:

In [140]:
bugs = 'roaches'
count = 13
area = 'living room'
print(f'Debugging {bugs=} {count=} {area=}')


Debugging bugs='roaches' count=13 area='living room'


## The String format() Method

In [141]:
print('We are the {} who say "{}!"'.format('knights', 'Ni'))


We are the knights who say "Ni!"


The brackets and characters within them (called format fields) are replaced with the objects passed into the str.format() method. A number in the brackets can be used to refer to the position of the object passed into the str.format() method.

In [142]:
print('{0} and {1}'.format('spam', 'eggs'))

print('{1} and {0}'.format('spam', 'eggs'))


spam and eggs
eggs and spam


In [143]:
#If keyword arguments are used in the str.format() method, their values are referred to by using the name of the argument.
print('This {food} is {adjective}.'.format(
      food='spam', adjective='absolutely horrible'))


# Positional and keyword arguments can be arbitrarily combined:

print('The story of {0}, {1}, and {other}.'.format('Bill', 'Manfred',
                                                   other='Georg'))

This spam is absolutely horrible.
The story of Bill, Manfred, and Georg.


In [155]:
table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 8637678}
print('Jack: {Jack:d}; Sjoerd: {Sjoerd:d}; Dcab: {Dcab:d}'.format(**table))

Jack: 4098; Sjoerd: 4127; Dcab: 8637678


In [156]:
for x in range(1, 11):
    print('{0:2d} {1:3d} {2:4d}'.format(x, x*x, x*x*x))

 1   1    1
 2   4    8
 3   9   27
 4  16   64
 5  25  125
 6  36  216
 7  49  343
 8  64  512
 9  81  729
10 100 1000


In [164]:
# old method, string interpolation.
# Given `format % values` (where format is a string), % conversion specifications in format are replaced with zero or more elements of values

import math
print('The value of pi is approximately=%5.2f.' % math.pi)

The value of pi is approximately= 3.14.


## Files

open() returns a file object, and is most commonly used with two positional arguments and one keyword argument: open(filename, mode, encoding=None)

```python
f = open('workfile', 'w', encoding="utf-8")
```
mode can be 'r' when the file will only be read, 'w' for only writing (an existing file with the same name will be erased), and 'a' opens the file for appending; any data written to the file is automatically added to the end. 'r+' opens the file for both reading and writing. The mode argument is optional; 'r' will be assumed if it’s omitted.


It is good practice to use the `with` keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point. Using with is also much shorter than writing equivalent try-finally blocks:

```python
>>> with open('workfile', encoding="utf-8") as f:
...     read_data = f.read()

>>> # We can check that the file has been automatically closed.
>>> f.closed
True
```

If you’re not using the with keyword, then you should call ```f.close()``` to close the file and immediately free up any system resources used by it.

If the end of the file has been reached, f.read() will return an empty string ('').

```python
>>> f.read()
'This is the entire file.\n'
>>> f.read()
''
```

`f.readline()` reads a single line from the file; a newline character (\n) is left at the end of the string, and is only omitted on the last line of the file if the file doesn’t end in a newline. This makes the return value unambiguous; if f.readline() returns an empty string, the end of the file has been reached, while a blank line is represented by '\n', a string containing only a single newline.

```python
>>> f.readline()
'This is the first line of the file.\n'
>>> f.readline()
'Second line of the file\n'
>>> f.readline()
''
```

For reading lines from a file, you can loop over the file object. This is memory efficient, fast, and leads to simple code:

```python
>>> for line in f:
...     print(line, end='')
...
This is the first line of the file.
Second line of the file
```

Don't do this, since it leaves file open:
```python
for line in open("myfile.txt"): #WRONG
    print(line, end="")
```

If you want to read all the lines of a file in a list you can also use `list(f)` or `f.readlines()`.


## JSON 

In [168]:
import json
x = [1, 'simple', 'list']
json.dumps(x) # to string
type(json.dumps(x))

'[1, "simple", "list"]'

str

Another variant of the dumps() function, called dump(), simply serializes the object to a text file. So if f is a text file object opened for writing, we can do this:

```python
json.dump(x, f)

# and then,  if f is a binary file or text file object which has been opened for reading:

x = json.load(f)
```

## Exceptions

In [166]:
class B(Exception):
    pass

class C(B):
    pass

class D(C):
    pass

for cls in [B, C, D]:
    try:
        raise cls()
    except D:
        print("D")
    except C:
        print("C")
    except B:
        print("B")

B
C
D


#### If the try statement reaches a break, continue or return statement, the finally clause will execute just prior to the break, continue or return statement’s execution.

If the finally clause executes a break, continue or return statement, exceptions are not re-raised.


If a finally clause includes a return statement, the returned value will be the one from the finally clause’s return statement, not the value from the try clause’s return statement.

In [169]:
def bool_return():
    try:
        return True
    finally:
        return False

bool_return()

False

# Classes



In [179]:
s = 'abc'
it = iter(s)

type(it).__next__(it)


next(it)

next(it)

next(it)



'a'

'b'

'c'

StopIteration: 

## super() method

The reason we use super is so that child classes that may be using cooperative multiple inheritance will call the correct next parent class function in the Method Resolution Order (MRO).

In Python 3, we can call it like this:

In [3]:
class Base(object):
    def __init__(self):
        print("Base created")

class ChildB(Base):
    def __init__(self):
        super().__init__()

In Python 2, we were required to call super like this with the defining class's name and self, but we'll avoid this from now on because it's redundant, slower (due to the name lookups), and more verbose (so update your Python if you haven't already!):

In [5]:
class ChildC(Base):
    def __init__(self):
        super(ChildC, self).__init__()

In [6]:
c = ChildC()

Base created


In [7]:
b = ChildB()

Base created


Without super, you are limited in your ability to use multiple inheritance because you hard-wire the next parent's call:

```python
Base.__init__(self) # Avoid this.
```


In [9]:
# What's the difference
class ChildA(Base):
    def __init__(self):
        Base.__init__(self)

class ChildB(Base):
    def __init__(self):
        super().__init__()

The primary difference in this code is that in ChildB you get a layer of indirection in the `__init__` with super, which uses the class in which it is defined to determine the next class's `__init__` to look up in the MRO.